# bravo_camera
- size: &realsense_size
    width: 0.25
    height: 0.20
  position:
    x: -0.494061
    y: 0.692729
    z: 0.400215
  fixture_orientation: "+y"
  offset: # From fixture tip to camera optical frame offset
    x: 0.02
    y: 0.05
    z: 0.09

# charlie_camera
- size: *realsense_size
  position:
    x: -1.201099
    y: 0.000400
    z: 0.403127
  fixture_orientation: "-x"
  offset: # From fixture tip to camera optical frame offset
    x: -0.02
    y: 0.02
    z: 0.09

# "left_camera"
- size: *realsense_size # Dimensions with 1.25 cm margin all around
  position:
    x: 0.9659536185112643
    y: -0.3803047341856819
    z: 0.3660681660928672
  fixture_orientation: "+x"
  offset: # From fixture tip to camera optical frame offset
    x: -0.05
    y: -0.05
    z: 0.09
