# bravo_camera
- size: &realsense_size
    width: 0.25
    height: 0.20
  position:
    x: -0.494061
    y: 0.692729
    z: 0.400215
  fixture_orientation: "+y"
  offset: # From fixture tip to camera optical frame offset
    x: 0.02
    y: 0.05
    z: 0.09

# charlie_camera
- size: *realsense_size
  position:
    x: -1.201099
    y: 0.000400
    z: 0.403127
  fixture_orientation: "-x"
  offset: # From fixture tip to camera optical frame offset
    x: -0.02
    y: 0.02
    z: 0.09

# Spare camera
- size: *realsense_size
  position:
    x: 0.659426
    y: 0.561549
    z: 0.308404
  fixture_orientation: "+y"
  offset: # From fixture tip to camera optical frame offset
    x: -0.03
    y: 0.00
    z: 0.09

# "left" camera
- size: *realsense_size
  position:
    x: 1.11
    y: -0.045
    z: 0.2675
  fixture_orientation: "+x"
  offset: # From fixture tip to camera optical frame offset
    x: -0.10
    y: 0.00
    z: 0.01
