- size: &realsense_size # Dimensions with 1.25 cm margin all around
    width: 0.12
    height: 0.04
  position:
    x: 0
    y: 0.45
    z: 0.35
  fixture_orientation: "+y"
  offset: # From fixture tip to camera optical frame offset
    x: 0.045
    y: 0
    z: 0.08

- size: *realsense_size
  position:
    x: -0.45
    y: -0.9
    z: 0.35
  fixture_orientation: "-y"
  offset: # From fixture tip to camera optical frame offset
    x: -0.045
    y: 0
    z: 0.08

- size: *realsense_size
  position:
    x: 1.2
    y: 0.1
    z: 0.45
  fixture_orientation: "+x"
  offset: # From fixture tip to camera optical frame offset
    x: -0.045
    y: 0
    z: 0.08

- size: *realsense_size
  position:
    x: -1.2
    y: 0.1
    z: 0.20
  fixture_orientation: "-x"
  offset: # From fixture tip to camera optical frame offset
    x: -0.045
    y: 0
    z: 0.08